version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce'
    container_name: gitlab
    restart: always
    hostname: ' '
    ports:
      - '4430:443'
      - '800:80'
      - '220:22'
    volumes:
      - './srv/gitlab/config:/etc/gitlab'
      - './srv/gitlab/logs:/var/log/gitlab'
      - './srv/gitlab/data:/var/opt/gitlab'

# sudo mkdir -p /srv/gitlab/config /srv/gitlab/logs /srv/gitlab/data
# sudo mkdir -p ./srv/gitlab/config ./srv/gitlab/logs ./srv/gitlab/data

sudo docker run --detach \
  --hostname 192.168.0.107 \
  --publish 4430:443 --publish 800:80 --publish 220:22 \
  --name gitlab \
  --restart always \
  # --volume ./srv/gitlab/config:/etc/gitlab \
  # --volume ./srv/gitlab/logs:/var/log/gitlab \
  # --volume ./srv/gitlab/data:/var/opt/gitlab \
  gitlab/gitlab-ce:latest