version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce'
    container_name: gitlab
    restart: always
    hostname: '192.168.0.107' # change
    ports:
      - '4430:443'
      - '800:80'
      - '220:22'
    volumes:
      - './srv/gitlab/backups:/var/opt/gitlab/backups'
      - './srv/gitlab/secrets/gitlab.rb:/etc/gitlab/gitlab.rb'
      - './srv/gitlab/secrets/gitlab-secrets.json:/etc/gitlab/gitlab-secrets.json'